version: '3'
services:
  reverseproxy: 
    build: ./reverseproxy
    ports:
      - 80:80
      - 443:443
      
  couchdb: 
    image: couchdb:2.3.0
    environment:
      COUCHDB_USER: ${COUCHDB_USER} 
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}