version: '3'
services:
  reverseproxy: 
    build: ./reverseproxy
    ports:
      - 80:80
      - 443:443
    restart: always
      
  couchdb: 
    image: couchdb:2.3.0
    environment:
      COUCHDB_USER: ${COUCHDB_USER} 
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - datavolume:/opt/couchdb/data
    restart: always
    ports:
      - 5984:5984
      

volumes:
  datavolume: